version: '3.8'
services:
  shopping-website:
    image: shopping-website:${BUILD_VERSION}
    container_name: shopping-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
    restart: always
